slack_clone/chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
	path('channels/search', views.search_channel, name='search_channels'),
	path('channels/', views.show_channels, name='channels'),
	path('channels/<int:channel_id>', views.show_channel, name='channel'),
	path('channels/add', views.add_channel, name='add_channel'),
	path('channels/add/chat/<int:friend_id>', views.open_chat, name='open_chat'),
]

slack_clone/message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
	path('channels/add_message/<int:channel_id>/', views.add_message, name='add_message'),
]

slack_clone/slack_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('chats.urls')),
    path('', include('message.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slack_clone/user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
		path('accounts/login/', views.login_view, name='login'),
		path('accounts/signup/', views.signup_view, name='signup'),
		path('accounts/logout/', views.logout_view, name='logout'),
		path('accounts/profile/<int:profile_id>', views.show_profile, name='show_profile'),
		path('accounts/profiles', views.show_profiles, name='show_profiles'),
		path('accounts/profiles/add/<int:friend_id>', views.add_friend, name='add_friend'),
]

slack_clone/chats/models.py
from django.db import models
from user_profile.models import Profile
from django.contrib.auth.models import User


class Channel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='channels')
    users = models.ManyToManyField(User)

slack_clone/message/models.py
from django.db import models
from user_profile.models import Profile
from chats.models import Channel


class Message(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="messages")
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="messages")

slack_clone/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    bio = models.TextField(blank=True)
    pic = models.ImageField(upload_to='media/images/')
    friends = models.ManyToManyField("self")

slack_clone/chats/views.py
from django.shortcuts import render, redirect
from .models import Channel
from message.models import Message
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from user_profile.models import Profile


def show_channels(request):
    channels = Channel.objects.all()
    return render(request, 'channels_list.html', {
        'channels': channels
        })

def search_channel(request):
    context = None
    if request.method != 'POST':
        return redirect('chats:channels')

    text = request.POST.get('search', '')
    results = Channel.objects.filter(
        Q(name__icontains=text) |
        Q(description__icontains=text)
        )

    return render(request, 'channels_list.html', {
            'channels': results,
        })

def show_channel(request, channel_id):
    channel = Channel.objects.get(id=channel_id)
    messages = Message.objects.filter(channel_id=channel.id)
    user = request.user
    channel.users.add(user)
    channel.save()

    return render(request, 'channel.html', {
        'channel': channel,
        'messages': messages,
        })

def add_channel(request):
    if request.method == "POST":
        name = request.POST['channel_name']
        description = request.POST['channel_description']
        creator_id = request.user.id
        channel = Channel(name=name, description=description, creator_id=creator_id)
        channel.save()
        return redirect('chats:channels')

def open_chat(request, friend_id):
    friend = User.objects.get(id=friend_id)
    user = request.user
    channel = Channel(name="{} & {}".format(user.username, friend.username), description=None, creator_id=user.id)
    channel.save(False)
    channel.users.add(friend)
    channel.save(False)
    channel.users.add(user)
    channel.save()
    messages = Message.objects.filter(channel_id=channel.id)
    return render(request, 'channel.html', {
            'channel': channel,
            'messages': messages,
        })

slack_clone/message/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from chats.models import Channel
from .models import Message


@login_required
def add_message(request, channel_id):
	channel = Channel.objects.get(pk=channel_id)
	if request.method == 'POST':
		text = request.POST['message_text']
		author = request.user.id
		pub_date = timezone.now()
		m = Message(text=text, author_id=author, pub_date=pub_date, channel_id=channel.id)
		m.save()
		return redirect('chats:channel', channel_id=channel.id)

slack_clone/user_profile/views.py
from django.shortcuts import render, redirect
from .models import Profile
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.conf import settings


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            profile = Profile.objects.get(user_id=user.id)
            return redirect('chats:channels')
        else:
            return redirect('user_profile:signup')

    return render(request, 'login.html')


@login_required(login_url='/accounts/login/')
def show_profile(request, profile_id):
    user_profile = Profile.objects.get(pk=profile_id)
    if request.method == 'POST' and request.FILES['image']:
        profile_pic = request.FILES['image']
        fs = FileSystemStorage(location='media/images', base_url='/media/images/')
        filename = fs.save(profile_pic.name, profile_pic)
        uploaded_file_url = fs.url(filename)
        user_profile.pic = uploaded_file_url
        user_profile.save()

    return render(request, 'profile.html', {
            'profile': user_profile,
        })

def logout_view(request):
    logout(request)
    return render(request, 'logout.html')


def signup_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        bio = request.POST['bio']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        user = User.objects.create_user(email=email, first_name=first_name, last_name=last_name, username=username, password=password)
        user.save()
        profile = Profile(user=user, bio=bio)
        profile.save()
        return redirect('user_profile:show_profile', profile_id=profile.id)

    return render(request, 'signup.html')

def show_profiles(request):
    profiles = Profile.objects.all()
    return render (request, 'profiles_list.html', {
            'profiles': profiles,
        })

def add_friend(request, friend_id):
        user = request.user
        user_profile = Profile.objects.get(user_id=user.id)
        friend = Profile.objects.get(id=friend_id)
        user_profile.friends.add(friend)
        user_profile.save()
        return redirect('user_profile:show_profiles')

slack_clone/chats/templates/channel.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5">
		<div class="col-md-3 mt-2 ml-3 mr-5">
			<h1>{{ channel.name }} channel</h1>
			<div class="card mt-3">
			  <div class="card-body">
			    <h5 class="card-text">{{ channel.description }}</h5>
			    <small>Channel opened by: {{ channel.creator.user }}</small>
			  </div>
			</div>
		    
			<div class="card mt-3">
			  <div class="card-body">
			    <h5 class="card-title">In the channel:</h5>
			    {% for user in channel.users.all %}
				<p class="card-text">{{ user }}</p>
				{% endfor %}
			  </div>
			</div>
		</div>
		<div class="col-md-7 ml-5">
			

		<ul class="list-group list-group-item-light">

			{% for message in messages %}
		  <li class="list-group-item {% if message.author_id != user.id %}list-group-item-light{% else %} list-group-item-dark {% endif %} d-flex justify-content-between align-items-center">
		  	{{ message.author.user }} says: 
			{{ message.text }}  
			<span class="badge badge-primary badge-pill">{{ message.pub_date }}</span>
  			</li>
  			{% endfor %}
  		</ul>
		  <hr>
		  
		  	<form method="POST" action="{% url 'message:add_message' channel.id %}">
		  		{% csrf_token %}
		  		<div class="input-group mb-3">
			  <input type="text" class="form-control" name="message_text" placeholder="Write a message">
			  <div class="input-group-append">
			    <button class="btn btn-outline-secondary" type="submit">Send</button>
			  </div>
			 </form>
		</div>		
	</div>
</div>

{% endblock %}

slack_clone/chats/templates/channels_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5">
		<div class="col-md-3 mt-2 mr-5">
			<form class="form-inline my-2 my-lg-0" method='POST' action="{% url 'chats:search_channels' %}">
				{% csrf_token %}
		      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">
		      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
		    </form>
		    <hr>
		    <form class="form-signin text-center mt-5" method='POST' action="{% url 'chats:add_channel' %}">
			 	{% csrf_token %}
				  <img class="mb-4" src="https://junkee.com/wp-content/uploads/2019/03/slack.jpg" alt="" width="100" height="72">
				  <h1 class="h3 mb-3 font-weight-normal">Open a new channel</h1>
				  <label for="channel_name" class="sr-only">Name</label>
				  <input type="text" name="channel_name" id="channel_name" class="form-control mb-2" placeholder="Name" required="" autofocus="">
				  <label for="channel_description" class="sr-only">Description</label>
				  <textarea class="form-control mb-2" id="bio" rows="3" name="channel_description" placeholder="Short Description"></textarea>
				  <button class="btn btn-lg btn-outline-info btn-block" type="submit">Add</button>
			 </form>				
		</div>
		<div class="col-md-8">
			<h1>Channels:</h1>
			{% for channel in channels %}
			{% if channel.description != None %}
			<div class="card mt-3">
			  <div class="card-body ">
			    <h5 class="card-title"> <a href="{% url 'chats:channel' channel.id %}" class="btn btn-outline-info btn-sm">Join</a> {{ channel.name }}</h5>
			    <p class="card-text">{{ channel.description }}.</p>
			    <small>{{ channel.creator.user }}</small>
			  </div>
			</div>
			{% endif %}
			{% endfor %}
		</div>
</div>

{% endblock %}

slack_clone/user_profile/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>Slack Clone</title>
</head>
<body>
	{% block nav %}
	<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
	  <a class="navbar-brand" href="#"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Slack_Technologies_Logo.svg/1280px-Slack_Technologies_Logo.svg.png" width="120" height="30"></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarText">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'chats:channels' %}">Channels</a>
	      </li>
	      {% if user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'user_profile:show_profile' user.profile.id %}">Your Profile</a>
	      </li>
	      {% else %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'user_profile:signup' %}">Signup</a>
	      </li>
	      {% endif %}
	    </ul>
	    {% if user.is_authenticated %}
	    <span class="navbar-text">
	      <a href="{% url 'user_profile:show_profile' user.profile.id %}"> {{ user.username }} </a>
	      <a href="{% url 'user_profile:logout' %}">Logout</a>
	    </span>
	    {% else %}
	    <span class="navbar-text">
	      <a href="{% url 'user_profile:login' %}">Login</a>
	    </span>
	    {% endif %}
	  </div>
	</nav>
	{% endblock %}
	{% block content %} {% endblock %}
</body>
</html>

slack_clone/user_profile/templates/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5 justify-content-center">
		<div class="col-3 text-center">
			 <form class="form-signin text-center" method='POST'>
			 	{% csrf_token %}
				  <img class="mb-4" src="https://junkee.com/wp-content/uploads/2019/03/slack.jpg" alt="" width="100" height="72">
				  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
				  <label for="username" class="sr-only">Username</label>
				  <input type="text" name="username" id="iusername" class="form-control mb-2" placeholder="Username" required="" autofocus="">
				  <label for="inputPassword" class="sr-only">Password</label>
				  <input type="password" name="password" id="inputPassword" class="form-control mb-3" placeholder="Password" required="">
				  <button class="btn btn-lg btn-info btn-block" type="submit">Sign in</button>
				  <p class="mt-5 mb-3 text-muted">©2019</p>
			 </form>				
		</div>
	</div>
</div>

{% endblock %}

slack_clone/user_profile/templates/logout.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5 justify-content-center">
		<div class="col-6">
			<div class="jumbotron">
			  <h1 class="display-4">You're Logged out!</h1>
			  	  <hr class="my-4">
			  <p class="lead">Click here to log back in:</p>
			  <a class="btn btn-primary btn-lg" href="{% url 'user_profile:login' %}" role="button">Login</a>
			</div>		
		</div>
	</div>
</div>

{% endblock %}

slack_clone/user_profile/templates/profile.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
            <form method="post">
                <div class="row mt-5">
                    <div class="col-md-4">
                    	<div class="profile-img">
                            <img src="{{ profile.pic }}">
                        </div>
                        <form method="POST" action="{% url 'user_profile:show_profile' profile.id %}" enctype="multipart/form-data" action="">
                            {% csrf_token %}
                            <div class="form-group">
                            <p class="card-text mt-3">Change your profile picture:</p>
                            <input class="form-control-file" type="file" name="image"><br>
                            <button type="submit" class="btn btn-primary">Upload</button>
                            </div>
                        </form>
                        <div class="card mt-3">
              <div class="card-body">
                <h5 class="card-title">Friends:</h5>
                {% for friend in profile.friends.all %}
                <a href="{% url 'user_profile:show_profile' friend.id %}">
                <p class="card-text">{{ friend.user.username }} <a href="{% url 'chats:open_chat' friend.id %}" class="btn btn-outline-info btn-sm ml-3">Chat</a></p>
                </a>
                {% endfor %}
              </div>
            </div>
        </div>

                    <div class="col-md-8">
                        <div class="profile-head">
                                    <h5>
                                        {{ profile.user.first_name }} {{ profile.user.last_name }}
                                    </h5>
                         
                            <ul class="list-group list-group-flush mt-5">
                                <li class="list-group-item mt-5">

                                </li>
                            </ul>
                        </div>
                    
                    
               <!--  <div class="row mt-3"> -->
                    <!-- <div class="col-md-4">
                        
                    </div> -->
                   <!--  <div class="col-md-8"> -->
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            			<div class="row">
                                            <div class="col-md-5 ml-3">
                                                <label>First Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ profile.user.first_name }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 ml-3">
                                                <label>Last Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ profile.user.last_name }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 ml-3">
                                                <label>Username</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ profile.user.username }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 ml-3">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <a href="{{ profile.user.email }}" target="_top">{{ profile.user.email }}</a>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-5 ml-3">
                                                <label>Bio</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ profile.bio }}</p>
                                            </div>
                                        </div>
                            	</div>                             
                            </div>
                            </div>
                <!-- </div> -->
                        </div>
                    </div>
                </div>
            </form>           
        </div>

{% endblock %}

slack_clone/user_profile/templates/profiles_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5">
		<div class="col-md-3 mt-2 mr-5">
			<form class="form-inline my-2 my-lg-0" method='POST' action="{% url 'chats:search_channels' %}">
				{% csrf_token %}
		      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">
		      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
		    </form>
		    <hr>				
		</div>
		<div class="col-md-8">
			<h1>Profiles:</h1>
			{% for profile in profiles %}
			<div class="card mt-3">
			  <div class="card-body ">
			  	{% if profile.user.username != user.username %}
			    <h5 class="card-title"> {{ profile.user.username }} <a href="{% url 'user_profile:add_friend' profile.id %}" class="btn btn-outline-info btn-sm ml-3">Add friend</a> </h5>
			    {% endif %}
			  </div>
			</div>
			{% endfor %}
		</div>
</div>

{% endblock %}

slack_clone/user_profile/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
	<div class="row mt-5 justify-content-center">
		<div class="col-3 text-center">
			 <form class="form-signup text-center" method='POST'>
			 	{% csrf_token %}
				  <img class="mb-4" src="https://junkee.com/wp-content/uploads/2019/03/slack.jpg" alt="" width="100" height="72">
				  <h1 class="h3 mb-3 font-weight-normal">Please create an account</h1>
				  <label for="first_name" class="sr-only">First Name</label>
				  <input type="text" name="first_name" id="first_name" class="form-control mb-2" placeholder="First Name" required="" autofocus="">
				  <label for="last_name" class="sr-only">Last Name</label>
				  <input type="text" name="last_name" id="last_name" class="form-control mb-2" placeholder="Last Name" required="" autofocus="">
				  <label for="bio" class="sr-only">Bio</label>
				  <textarea class="form-control mb-2" id="bio" rows="3" name="bio" placeholder="Short Bio"></textarea>
				  <label for="email" class="sr-only">Email</label>
				  <input type="email" name="email" id="email" class="form-control mb-2" placeholder="Email" required="" autofocus="">
				  <label for="username" class="sr-only">Username</label>
				  <input type="text" name="username" id="iusername" class="form-control mb-2" placeholder="Username" required="" autofocus="">
				  <label for="inputPassword" class="sr-only">Password</label>
				  <input type="password" name="password" id="inputPassword" class="form-control mb-3" placeholder="Password" required="">
				  <button class="btn btn-lg btn-info btn-block" type="submit">Sign up</button>
				  <p class="mt-5 mb-3 text-muted">©2019</p>
			 </form>				
		</div>
	</div>
</div>

{% endblock %}